cania_azucar/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include  # Visualizar imagenes en pagina-admin
    # https://docs.djangoproject.com/en/3.1/ref/settings/#media-root

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include(('users.urls','users'), namespace='users')),
    path("", include(('detections.urls','detections'), namespace='detections'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

detections/urls.py
"""Detections URLs."""

# Django
from django.urls import path

# View
from detections import views

urlpatterns = [
        # Management
    path(
        route='',
        view=views.IndexView.as_view(),
        name='home'
    ),
    path(
        route='new-detection/',
        view=views.NewDetectionView.as_view(),
        name='new_detection'
    ),
    path(
        route='detections/',
        view=views.AllDetectionsView.as_view(),
        name='all_detections',
    ),
    path(
        route='last_detection/',  # Detection Management
        view=views.LastDetectionView.as_view(),
        name='last_detection'
    ),
    path(
        route='<str:name>/',  # Detection Management
        view=views.DetectionDetailView.as_view(),
        name='detection_detail'
    ),

    #path("logout/", LogoutView.as_view(), name="logout")
]

users/urls.py
"""Urls users."""

# Django
from django.urls import path
#from django.contrib.auth.views import LogoutView

# View
from users import views

urlpatterns = [
        # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route='me/profile/',
        view=views.ProfileDetailView.as_view(),
        name='profile'

    ),
    #path('register/', register_user, name="register"),
    #path("logout/", LogoutView.as_view(), name="logout")
]

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a href="https://www.ipn.mx"
                   class="font-weight-bold ml-1" target="_blank">Instituto Politecnico Nacional</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               <a href="https://www.upiita.ipn.mx/">UPIITA</a>
               - code with <a target="_blank" href="https://www.djangoproject.com/">Django</a>.
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a target="_blank"
                 href="https://www.ipn.mx/"
                 class="font-weight-bold ml-1">Instituto Politecnico Nacional</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://www.upiita.ipn.mx/"
                 class="font-weight-bold ml-1" target="_blank"> UPIITA</a>
            </div>
          </div>
        </div>
      </footer>

templates/includes/navigation-fullscreen.html
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
      <div class="container px-4">
        <a class="navbar-brand" href="/">
          <img src="/static/assets/img/brand/logo-white.png" width="250"/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-main">
          <!-- Collapse header -->
          <div class="navbar-collapse-header d-md-none">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="/">
                  <img src="/static/assets/img/brand/logo-black.png">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <!-- Navbar items -->
          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <a target="_blank"
                 class="nav-link nav-link-icon"
                 href="https://github.com/root1224/Proyecto_Pagina">
                <i class="ni ni-ui-04"></i>
                <span class="nav-link-inner--text">Source Code</span>
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank"
                 class="nav-link nav-link-icon" href="https://www.gob.mx/conadesuca/">
                <i class="ni ni-spaceship"></i>
                <span class="nav-link-inner--text">CONADESUCA</span>
              </a>
            </li>

          </ul>
        </div>
      </div>
    </nav>

templates/includes/navigation.html
{% load static %}

    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="/">Dashboard</a>
        <!-- Form -->
        <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
          <div class="form-group mb-0">
            <div class="input-group input-group-alternative">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
              </div>
              <input class="form-control" placeholder="Search" type="text">
            </div>
          </div>
        </form>
        <!-- User -->
        <ul class="navbar-nav align-items-center d-none d-md-flex">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  <div class="media">
                    {% if request.user.profile.picture %}
                          <img class="rounded-circle" src="{{ request.user.profile.picture.url }}" />
                    {% else%}
                          <img class="rounded-circle" src="{% static 'assets/img/theme/default_profile.jpg' %}"/>
                    {% endif %}
                  </div>
                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">
                    {{ request.user.username }}
                  </span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
              <div class=" dropdown-header noti-title">
                <h6 class="text-overflow m-0">Bienvenido!</h6>
              </div>
              <a href="{% url "users:profile" %}" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>Mi perfil</span>
              </a>
              <a href="/profile.html" class="dropdown-item">
                <i class="ni ni-settings-gear-65"></i>
                <span>Ajustes</span>
              </a>
              <a href="https://appseed.us" target="_blank" class="dropdown-item">
                <i class="ni ni-support-16"></i>
                <span>Soporte</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'users:logout' %}" class="dropdown-item">
                <i class="ni ni-user-run"></i>
                <span>Salir</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <!-- End Navbar -->

templates/includes/scripts-fullscreen.html
  <!--   Core   -->
  <script src="/static/assets/js/plugins/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!--   Optional JS   -->
  <!--   Argon JS   -->
  <script src="/static/assets/js/argon-dashboard.min.js?v=1.1.0"></script>

templates/includes/scripts.html
  <!--   Core   -->
  <script src="/static/assets/js/plugins/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!--   Optional JS   -->
  <script src="/static/assets/js/plugins/chart.js/dist/Chart.min.js"></script>
  <script src="/static/assets/js/plugins/chart.js/dist/Chart.extension.js"></script>

  <!--   G.Maps   -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <!--   Argon JS   -->
  <script src="/static/assets/js/argon-dashboard.min.js?v=1.1.0"></script>

templates/includes/sidenav.html
{% load static %}
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="/">
        <img src="/static/assets/img/brand/logo-black.png" class="navbar-brand-img" alt="..." width="200" height="80">
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
  
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                {% if request.user.profile.picture %}
                      <img alt="Image placeholder" src="{{ request.user.profile.picture.url }}" />
                {% else %}
                      <img alt="Image placeholder" src="{% static 'assets/img/theme/default_profile.jpg' %}"/>
                {% endif %}
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>Settings</span>
            </a>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-calendar-grid-58"></i>
              <span>Activity</span>
            </a>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'users:logout' %}" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="./index.html">
                <img src="/static/assets/img/brand/logo-black.png">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Form -->
        <form class="mt-4 mb-3 d-md-none">
          <div class="input-group input-group-rounded input-group-merge">
            <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <span class="fa fa-search"></span>
              </div>
            </div>
          </div>
        </form>
        <!-- Navigation -->
        <ul class="navbar-nav">
          <li class="nav-item  class=" active" ">
          <a class=" nav-link active " href="{% url "detections:home" %}"> <i class="ni ni-tv-2 text-primary"></i> Estres Hidrico
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url "detections:all_detections" %}">
              <i class="ni ni-planet text-blue"></i> Detections
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url "detections:new_detection" %}">
              <i class="ni ni-bullet-list-67 text-info"></i> New detection
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url "detections:last_detection" %}">
              <i class="ni ni-pin-3 text-orange"></i> Last detection
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url "users:profile" %}">
              <i class="ni ni-single-02 text-yellow"></i> User profile
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">
              <i class="ni ni-user-run text-red"></i> Logout
            </a>
          </li>
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading text-muted">Links</h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">

          <li class="nav-item">
            <a target="_blank"
               class="nav-link nav-link-icon"
               href="https://www.gob.mx/conadesuca/">
              <i class="ni ni-world-2"></i>
              <span class="nav-link-inner--text">CONADESUCA</span>
            </a>
          </li>

        <!--  <li class="nav-item">
            <a class="nav-link" target="_blank"
               href="https://www.creative-tim.com/templates/django">
              <i class="ni ni-spaceship"></i> More Django Apps
            </a>
          </li> -->

        </ul>
      </div>
    </div>
  </nav>