cania_azucar/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include  # Visualizar imagenes en pagina-admin
    # https://docs.djangoproject.com/en/3.1/ref/settings/#media-root

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include(('users.urls','users'), namespace='users')),
    path("", include(('detections.urls','detections'), namespace='detections'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

detections/urls.py
"""Detections URLs."""

# Django
from django.urls import path

# View
from detections import views

urlpatterns = [
        # Management
    path(
        route='',
        view=views.IndexView.as_view(),
        name='home'
    ),
    path(
        route='new-detection/',
        view=views.NewDetectionView.as_view(),
        name='new_detection'
    ),
    path(
        route='detections/',
        view=views.AllDetectionsView.as_view(),
        name='all_detections',
    ),
    path(
        route='last_detection/',  # Detection Management
        view=views.LastDetectionView.as_view(),
        name='last_detection'
    ),
    path(
        route='<str:name>/',  # Detection Management
        view=views.DetectionDetailView.as_view(),
        name='detection_detail'
    ),

    #path("logout/", LogoutView.as_view(), name="logout")
]

users/urls.py
"""Urls users."""

# Django
from django.urls import path
#from django.contrib.auth.views import LogoutView

# View
from users import views

urlpatterns = [
        # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route='me/profile/',
        view=views.ProfileDetailView.as_view(),
        name='profile'

    ),
    #path('register/', register_user, name="register"),
    #path("logout/", LogoutView.as_view(), name="logout")
]

detections/models.py
""" Detections models."""
# Django
# https://github.com/django/django/blob/master/django/contrib/auth/models.py
from django.db import models # https://docs.djangoproject.com/en/3.1/ref/models/fields/
from django.contrib.auth.models import User



class Detection(models.Model):
    """ Profile model.
    Proxy model that extends the base data with other
    information.
    """
    DEAD = 'dead'
    SAVE = 'save'
    GOOD = 'good'

    SATATUS_OF_FIELD = [
        (DEAD, 'Dead'),
        (SAVE, 'Save'),
        (GOOD, 'Good'),
    ]

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    profile = models.ForeignKey('users.Profile', on_delete=models.SET_NULL, null=True)

    name = models.CharField(max_length=20)
    picture = models.ImageField(
        upload_to='detections/RGB',
    )

    picture_ndvi = models.ImageField(
        upload_to='detections/NDVI'
    )
    picture_savi = models.ImageField(
        upload_to='detections/SAVI'
    )
    picture_evi2 = models.ImageField(
        upload_to='detections/EVI2'
    )


    satatus_of_field = models.CharField(
        max_length=10,
        choices=SATATUS_OF_FIELD,
        default=GOOD,
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Return detection name. """
        return self.name


class Note(models.Model):
    """ Note model."""
    note_detection = models.ForeignKey(Detection,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.CharField(max_length=100)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    #def get_notes(self):
    #    return "\n".join([note.name for note in self.notes.all()])

detections/forms.py
"""Detection forms."""

# Django
from django import forms

# Models
from detections.models import Detection, Note


class DetectionForm(forms.ModelForm):
    """Detection model form."""

    class Meta:
        """Form settings."""
        model = Detection
        fields = ('user', 'name', 'picture', 'picture_ndvi', 'satatus_of_field')

detections/views.py
"""Detections views."""
# Django
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView
from django.shortcuts import redirect
from django_tables2 import SingleTableView
from django.views.generic.base import TemplateView
from django.shortcuts import render


# Forms
from detections.forms import DetectionForm

# Models
from detections.models import Detection, Note

# MyApps
from azucar.app import CalculateVi, MakeCloustering
from azucar.SaveFiles import SaveFile,SaveDetection


class IndexView(LoginRequiredMixin, ListView):
    """Return Index."""
    template_name = 'detections/index.html'
    model = Detection
    context_object_name = 'detetions'

class AllDetectionsView(LoginRequiredMixin, ListView):
    """Return detections."""
    template_name = 'detections/all.html'
    model = Detection
    ordering = ('-created',)
    paginate_by = 5
    context_object_name = 'detections'

class DetectionDetailView(LoginRequiredMixin, DetailView, SingleTableView):
    """Detection detail view."""
    template_name = 'detections/detail.html'
    slug_field = 'name'
    slug_url_kwarg = 'name'
    model = Detection
    context_object_name = 'detection'

    def __init__(self, *args, **kwargs):
        super(DetectionDetailView, self).__init__(*args, **kwargs)
        self.object_list = self.get_queryset()

    def get_context_data(self, **kwargs):
        """Add detection's notes to context."""
        context = super().get_context_data(**kwargs)
        detection = self.get_object()
        context['notes'] = Note.objects.filter(note_detection=detection).order_by('-created')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data()
        if 'cloustering_ndvi' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster_ndvi']) != 0:
                number = request.POST['n_clouster_ndvi']
                type_vi = 'ndvi'
                picture_url = detection.picture_ndvi.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'cloustering_savi' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster_savi']) != 0:
                number = request.POST['n_clouster_savi']
                type_vi = 'savi'
                picture_url = detection.picture_savi.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'cloustering_evi2' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster_evi2']) != 0:
                number = request.POST['n_clouster_evi2']
                type_vi = 'evi2'
                picture_url = detection.picture_evi2.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'delete' in request.POST:
            id = request.POST['id_note']
            note_instance= Note.objects.get(id=id)
            note_instance.delete()

        return render(request, 'detections/detail.html', context)


class LastDetectionView(LoginRequiredMixin, DetailView, SingleTableView):
    """Last detection view."""
    template_name = 'detections/detail.html'
    model = Detection
    context_object_name = 'detection'

    def __init__(self, *args, **kwargs):
        super(LastDetectionView, self).__init__(*args, **kwargs)
        self.object_list = self.get_queryset()

    def get_object(self, queryset=None):
        object_instance = Detection.objects.all().order_by('-created').first()
        return object_instance

    def get_context_data(self, **kwargs):
        """Add detection's notes to context."""
        context = super().get_context_data(**kwargs)
        detection = self.get_object()
        context['notes'] = Note.objects.filter(note_detection=detection).order_by('-created')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data()
        if 'cloustering_ndvi' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster']) != 0:
                number = request.POST['n_clouster']
                type_vi = 'ndvi'
                picture_url = detection.picture_ndvi.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'cloustering_savi' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster']) != 0:
                number = request.POST['n_clouster']
                type_vi = 'savi'
                picture_url = detection.picture_savi.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'cloustering_evi2' in request.POST:
            detection = self.get_object()
            if int(request.POST['n_clouster']) != 0:
                number = request.POST['n_clouster']
                type_vi = 'evi2'
                picture_url = detection.picture_evi2.url

                MakeCloustering(request.user,int(number),picture_url)
                context['done_clouster'] = type_vi

        elif 'delete' in request.POST:
            id = request.POST['id_note']
            note_instance= Note.objects.get(id=id)
            note_instance.delete()

        return render(request, 'detections/detail.html', context)


class NewDetectionView(LoginRequiredMixin, TemplateView):
    """New detection view."""
    template_name = "detections/new.html"

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

    def post(self, request, *args, **kwargs):
        if 'detect' in request.POST:
            files_detection = request.FILES.getlist('files')
            if files_detection:
                if len(files_detection) == 3:
                    extention = []
                    if not any("RGB" in s.name for s in files_detection):
                        extention.append("RGB")
                    if not any("NIR" in s.name for s in files_detection):
                        extention.append("NIR")
                    if not any("RED" in s.name for s in files_detection):
                        extention.append("RED")

                    if not extention:
                        for request_file in files_detection:
                            SaveFile(request_file, request.user.username)

                        CalculateVi(request.user.username)
                        state='dead'
                        context = {
                            'save_detect' : True,
                            'state': state
                            }
                    else:
                        context = { 'msg' : 'Select files: '+','.join([str(n) for n in extention]) }

                else:
                    context = {
                        'msg' : 'Select three files.'
                    }

            else:
                context = {
                    'msg' : 'Select files.'
                }
            return render(request, self.template_name, context)

        elif 'save' in request.POST:
            user = request.user
            profile = request.user.profile
            detection_name = request.POST["name"]
            status = request.POST["satatus_of_field"]
            note_name = request.POST.getlist('note_name')
            note_text = request.POST.getlist('note_text')

            SaveDetection(request,user,profile,detection_name,status,note_name,note_text)
            return redirect('detections:last_detection')


        return render(request, self.template_name)

templates/detections/all-detections.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
          <!-- Card stats -->
          {% include "detections/cards-status.html" %}
        </div>
      </div>
    </div>

    <div class="container-fluid mt--7">

      <!-- Dark table -->
      <div class="row mt-5">
        <div class="col">
          <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
              <h3 class="text-white mb-0">Detections</h3>
            </div>
            <div class="table-responsive">
              <table class="table align-items-center table-dark table-flush">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Status</th>
                    <th scope="col">Created</th>
                    <th scope="col">Creator</th>
                    <th scope="col">Water Streess</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>

                  {% for detection in detections %}
                    {% include "detections/table-detections.html" %}
                  {% endfor %}

                </tbody>
              </table>
            </div>
            <div class="card-footer py-4 bg-default shadow">

              <nav aria-label="...">
                {% if page_obj.has_other_pages %}
                  {% include "pagination.html" %}
                {% endif%}
              </nav>

            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/detections/all.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
          <!-- Card stats -->
          {% include "detections/cards-status.html" %}
        </div>
      </div>
    </div>

    <div class="container-fluid mt--7">

      <!-- Dark table -->
      <div class="row mt-5">
        <div class="col">
          <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
              <h3 class="text-white mb-0">Detections</h3>
            </div>
            <div class="table-responsive">
              <table class="table align-items-center table-dark table-flush">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Status</th>
                    <th scope="col">Created</th>
                    <th scope="col">Creator</th>
                    <th scope="col">Water Streess</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>

                  {% for detection in detections %}
                    {% include "detections/table.html" %}
                  {% endfor %}

                </tbody>
              </table>
            </div>
            <div class="card-footer py-4 bg-default shadow">

              <nav aria-label="...">
                {% if page_obj.has_other_pages %}
                  {% include "pagination.html" %}
                {% endif%}
              </nav>

            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/detections/new-detection.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

{% load static %}

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 600px; background-image: url(/static/assets/img/theme/perfile_background.jpg); background-size: cover; background-position: center top;">
    </div>

    <div class="container-fluid mt--13">

      <form action="{% url 'detections:new_detection' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">

              <div class="row justify-content-center">
                <div class="justify-content-center">
                  <img id="new" width="350px" src="{% static 'assets/img/theme/default_image.jpg' %}" alt="your image" />
                </div>
              </div>

              <div class="row justify-content-center mt-4">
                <div class="d-flex justify-content-between">
                  <div class="media-body">
                    <p class="btn btn-sm btn-default justify-content-center">
                      <input type="file" name="picture" onchange="readURL(this);"/>
                    </p>
                  </div>
                </div>
              </div>

          </div>

          <div class="col-xl-8 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                  <div class="row align-items-center">
                    <div class="col-8">
                      <h3 class="mb-0">New detection</h3>
                    </div>
                    <div class="col-4 text-right">
                      <button type="submit" class="btn btn-sm btn-primary btn-block ">Save detection</button>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <h6 class="heading-small text-muted mb-4">Information</h6>
                    <div class="pl-lg-4">
                      <div class="row">
                        <div class="col-lg-6">
                          <div class="form-group">
                            <label class="form-control-label" for="input-username">Username</label>
                            <input disabled
                              type="text"
                              name="username"
                              id="input-username"
                              class="form-control form-control-alternative"
                              placeholder="Username"
                              value="{{ request.user.username }}"
                            >
                          </div>
                        </div>
                        <div class="col-lg-6">
                          <div class="form-group">
                            <label class="form-control-label" for="input-email">Created</label>
                            <input disabled
                              class="form-control form-control-alternative"
                              placeholder="{% now "SHORT_DATETIME_FORMAT" %}"
                            >
                          </div>
                        </div>
                      </div>
                      <div class="row justify-content-center">
                        <div class="col-lg-6 ">
                          <div class="form-group">
                            <label class="form-control-label" for="input-first-name">Status of Field</label>
                            <input disabled
                              type="text"
                              name="satatus_of_field"
                              id="input-satatus-of-field"
                              class="form-control form-control-alternative"
                              placeholder="None"

                            >
                          </div>
                        </div>
                      </div>
                    </div>
                    <hr class="my-4" />
                    <!-- Description -->
                    <h6 class="heading-small text-muted mb-4">Notes</h6>
                    <div class="pl-lg-4">
                      {# Phone number field #}
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Phone number</label>
                        <input
                          type="text"
                          name="phone_number"
                          id="input-last-name"
                          class="form-control form-control-alternative"
                          placeholder="Phone number"
                          value="{{ profile.phone_number }}"
                        >
                      </div>
                    </div>
                </div>
            </div>
          </div>
      </div>
      </form>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/detections/new-note.html
{% include "includes/scripts.html" %}
<form method="POST" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Create new Note</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

templates/detections/new.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

{% load static %}

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 600px; background-image: url(/static/assets/img/theme/perfile_background.jpg); background-size: cover; background-position: center top;">
    </div>

    <div class="container-fluid mt--13">

      <form action="{% url 'detections:new_detection' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
            <div class="card bg-gradient-default shadow">

              <div class="card-header bg-transparent">
                <div class="row align-items-center">
                  <div class="col">
                    <h6 class="text-uppercase text-light ls-1 mb-1">Detection Photo</h6>
                  </div>
                  <div class="col">
                    <ul class="nav nav-pills justify-content-end">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Type</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item " id="rgb-tab" data-toggle="tab" href="#rgb" role="tab" aria-controls="rgb" >RGB</a>
                          <a class="dropdown-item" href="#">Without ground</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" id="ndvi-tab" data-toggle="tab" href="#ndvi" role="tab" aria-controls="ndvi" >NDVI</a>
                          <a class="dropdown-item" id="savi-tab" data-toggle="tab" href="#savi" role="tab" aria-controls="savi" >SAVI</a>
                          <a class="dropdown-item" id="evi2-tab" data-toggle="tab" href="#evi2" role="tab" aria-controls="evi2" >EVI2</a>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>

              <div class="card-body">
                <div class="tab-content card shadow border-0">
                  <!-- New RGB -->
                  <div class="tab-pane fade show active" id="rgb" role="tabpanel" aria-labelledby="rgb-tab">
                    {% if save_detect %}
                      <img width="272px" name="picture" src="{{MEDIA_URL}}/temp/bands/{{request.user.username}}/RGB_temp.JPG" alt="RGB" />
                    {% else %}
                      <img width="276px" src="{% static 'assets/img/theme/default_image.jpg' %}" alt="RGB"/>
                    {% endif %}
                  </div>

                  <!-- New NDVI -->
                  <div class="tab-pane fade" id="ndvi" role="tabpanel" aria-labelledby="ndvi-tab">
                    {% if save_detect %}
                      <img width="272px" name="picture_ndvi" src="{{MEDIA_URL}}/temp/results/{{request.user.username}}/NDVI.jpg" alt="NDVI" />
                    {% else %}
                      <img width="276px" src="{% static 'assets/img/theme/default_image.jpg' %}"/>
                    {% endif %}
                  </div>

                  <!-- New SAVI -->
                  <div class="tab-pane fade" id="savi" role="tabpanel" aria-aria-controls="savi-tab">
                    {% if save_detect %}
                      <img width="272px" name="picture_savi" src="{{MEDIA_URL}}/temp/results/{{request.user.username}}/SAVI.jpg" alt="SAVI" />
                    {% else %}
                      <img width="276px" src="{% static 'assets/img/theme/default_image.jpg' %}"/>
                    {% endif %}
                  </div>

                  <!-- New EVI2 -->
                  <div class="tab-pane fade" id="evi2" role="tabpanel" aria-aria-controls="evi2-tab">
                    {% if save_detect %}
                      <img width="272px" name="picture_evi2" src="{{MEDIA_URL}}/temp/results/{{request.user.username}}/EVI2.jpg" alt="EVI2" />
                    {% else %}
                      <img width="276px" src="{% static 'assets/img/theme/default_image.jpg' %}"/>
                    {% endif %}
                  </div>

                </div>
              </div>

            </div>
          </div>

          <div class="col-xl-8 order-xl-1">
            <div class="card bg-secondary shadow">
              {% include "detections/new-data.html" %}
            </div>
          </div>
        </div>
      </form>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/detections/table-detections.html
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <a href="{% url "detections:detection_detail" detection.name %}"> 
          <span style="color:white" class="mb-0 text-sm">{{ detection.name }}</span>
        </a>
      </div>
    </div>
  </th>
  <td>
    <span class="badge badge-dot mr-4">
      {% if detection.satatus_of_field == 'dead' %}
        <i class="bg-danger"></i> DEAD
      {% elif detection.satatus_of_field == 'save' %}
        <i class="bg-warning"></i> SAVE
      {% else %}
        <i class="bg-success"></i> GOOD
      {% endif %}
    </span>
  </td>
  <td>
    {{ detection.created }}
  </td>
  <td>
    <div class="avatar-group">
      <a href="#" class="avatar avatar-sm" data-toggle="tooltip" data-original-title="{{ detection.user.get_full_name }}">
        <img alt="Image placeholder" src="{{ detection.profile.picture.url }}" class="rounded-circle">
      </a>
    </div>
  </td>
  <td>
    <div class="d-flex align-items-center">
      <span class="mr-2">60%</span>
      <div>
        <div class="progress">
          <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
        </div>
      </div>
    </div>
  </td>
  <td class="text-right">
    <div class="dropdown">
      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
  </td>
</tr>

templates/detections/table.html
<tr>
  <th scope="row">
    <div class="media align-items-center">
      <div class="media-body">
        <a href="{% url "detections:detection_detail" detection.name %}"> 
          <span style="color:white" class="mb-0 text-sm">{{ detection.name }}</span>
        </a>
      </div>
    </div>
  </th>
  <td>
    <span class="badge badge-dot mr-4">
      {% if detection.satatus_of_field == 'dead' %}
        <i class="bg-danger"></i> DEAD
      {% elif detection.satatus_of_field == 'save' %}
        <i class="bg-warning"></i> SAVE
      {% else %}
        <i class="bg-success"></i> GOOD
      {% endif %}
    </span>
  </td>
  <td>
    {{ detection.created }}
  </td>
  <td>
    <div class="avatar-group">
      <a href="#" class="avatar avatar-sm" data-toggle="tooltip" data-original-title="{{ detection.user.get_full_name }}">
        <img alt="Image placeholder" src="{{ detection.profile.picture.url }}" class="rounded-circle">
      </a>
    </div>
  </td>
  <td>
    <div class="d-flex align-items-center">
      <span class="mr-2">60%</span>
      <div>
        <div class="progress">
          <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
        </div>
      </div>
    </div>
  </td>
  <td class="text-right">
    <div class="dropdown">
      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
  </td>
</tr>